-- Script was generated by Devart dbForge Studio Express for MySQL, Version 6.0.622.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 14.05.2014 17:21:27
-- Server version: 5.5.25
-- Client version: 4.1

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

-- 
-- Set default database
--
USE raspisanie;

--
-- Definition for table department
--
DROP TABLE IF EXISTS department;
CREATE TABLE department (
  ID_dep INT(11) NOT NULL AUTO_INCREMENT,
  Name VARCHAR(255) NOT NULL,
  PRIMARY KEY (ID_dep)
)
ENGINE = INNODB
AUTO_INCREMENT = 2
AVG_ROW_LENGTH = 16384
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table groups
--
DROP TABLE IF EXISTS groups;
CREATE TABLE groups (
  ID_group INT(10) NOT NULL AUTO_INCREMENT,
  Number_Group VARCHAR(10) NOT NULL,
  Form_of_study TINYINT(4) NOT NULL,
  PRIMARY KEY (ID_group)
)
ENGINE = INNODB
AUTO_INCREMENT = 8
AVG_ROW_LENGTH = 2340
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table classroom
--
DROP TABLE IF EXISTS classroom;
CREATE TABLE classroom (
  ID_Classroom INT(11) NOT NULL AUTO_INCREMENT,
  Number_classroom VARCHAR(10) NOT NULL,
  ID_Department INT(11) NOT NULL,
  Building TINYINT(4) NOT NULL,
  PRIMARY KEY (ID_Classroom),
  CONSTRAINT FK_Classroom_department_ID_dep FOREIGN KEY (ID_Department)
    REFERENCES department(ID_dep) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 46
AVG_ROW_LENGTH = 744
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table lecturer
--
DROP TABLE IF EXISTS lecturer;
CREATE TABLE lecturer (
  ID_Lecturer INT(11) NOT NULL AUTO_INCREMENT,
  Family VARCHAR(255) NOT NULL,
  Department_ID INT(11) NOT NULL,
  PRIMARY KEY (ID_Lecturer),
  CONSTRAINT FK_lecturer_department_ID_dep FOREIGN KEY (Department_ID)
    REFERENCES department(ID_dep) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 126
AVG_ROW_LENGTH = 399
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table timetable
--
DROP TABLE IF EXISTS timetable;
CREATE TABLE timetable (
  ID_Timetable INT(11) NOT NULL AUTO_INCREMENT,
  ID_Grup INT(11) NOT NULL,
  ID_Lecturer INT(11) DEFAULT NULL,
  ID_classroom INT(11) DEFAULT NULL,
  Time TINYINT(4) NOT NULL,
  Date DATE NOT NULL,
  Type TINYINT(4) NOT NULL,
  Subject VARCHAR(255) NOT NULL,
  Comment VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (ID_Timetable),
  CONSTRAINT FK_Timetable_classroom_ID_Classroom FOREIGN KEY (ID_classroom)
    REFERENCES classroom(ID_Classroom) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT FK_Timetable_groups_ID_group FOREIGN KEY (ID_Grup)
    REFERENCES groups(ID_group) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT FK_Timetable_lecturer_ID_Lecturer FOREIGN KEY (ID_Lecturer)
    REFERENCES lecturer(ID_Lecturer) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 4841
AVG_ROW_LENGTH = 102
CHARACTER SET utf8
COLLATE utf8_general_ci;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;